default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ScanViewer_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: ScanViewer_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: ScanViewer_production
  username: ScanViewer
  password: <%= ENV['SCANVIEWER_DATABASE_PASSWORD'] %>
